# Generated by Django 2.1.1 on 2018-09-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lender_books', '0004_auto_20180921_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pre_save',
            field=models.CharField(default=1, editable=False, max_length=48),
            preserve_default=False,
        ),
    ]
