# Generated by Django 2.1.1 on 2018-09-21 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lender_books', '0005_book_pre_save'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pre_save',
            new_name='pre_save_status',
        ),
    ]
